// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Issue struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Content   sql.NullString `json:"content"`
	Priority  sql.NullString `json:"priority"`
	Status    string         `json:"status"`
	Assignee  sql.NullString `json:"assignee"`
	ProjectID sql.NullString `json:"project_id"`
	TeamID    string         `json:"team_id"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	Label     sql.NullString `json:"label"`
	OwnerID   string         `json:"owner_id"`
}

type IssueAssignee struct {
	IssueID string `json:"issue_id"`
	UserID  string `json:"user_id"`
}

type Project struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Status      sql.NullString `json:"status"`
	Priority    sql.NullString `json:"priority"`
	WorkspaceID string         `json:"workspace_id"`
	TeamID      string         `json:"team_id"`
	LeaderID    sql.NullString `json:"leader_id"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Label       sql.NullString `json:"label"`
	CreatedBy   string         `json:"created_by"`
}

type ProjectMember struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

type Team struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	WorkspaceID string         `json:"workspace_id"`
	LeaderID    sql.NullString `json:"leader_id"`
}

type TeamMember struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Email        string `json:"email"`
	Roles        string `json:"roles"`
}

type View struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedBy string `json:"created_by"`
	TeamID    string `json:"team_id"`
}

type ViewGroupBy struct {
	ViewID  string `json:"view_id"`
	GroupBy string `json:"group_by"`
}

type ViewIssue struct {
	ViewID  string `json:"view_id"`
	IssueID string `json:"issue_id"`
}

type Workspace struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

type WorkspaceMember struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}
