// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddAssigneeToIssue(ctx context.Context, arg AddAssigneeToIssueParams) error
	AddGroupByToView(ctx context.Context, arg AddGroupByToViewParams) error
	AddIssueToView(ctx context.Context, arg AddIssueToViewParams) error
	AddMemberToProject(ctx context.Context, arg AddMemberToProjectParams) error
	AddMemberToTeam(ctx context.Context, arg AddMemberToTeamParams) error
	AddMemberToWorkspace(ctx context.Context, arg AddMemberToWorkspaceParams) error
	CreateIssue(ctx context.Context, arg CreateIssueParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) error
	CreateTeam(ctx context.Context, arg CreateTeamParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateView(ctx context.Context, arg CreateViewParams) error
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteIssue(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
	DeleteTeam(ctx context.Context, id string) error
	DeleteTeamFromTeamMembers(ctx context.Context, teamID string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteView(ctx context.Context, id string) error
	DeleteWorkspace(ctx context.Context, id string) error
	GetIssueByID(ctx context.Context, id string) (Issue, error)
	GetIssueByUserID(ctx context.Context, userID string) ([]Issue, error)
	GetLeaderByTeamID(ctx context.Context, id string) (sql.NullString, error)
	GetOwnerByTeamID(ctx context.Context, id string) (string, error)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	GetProjectsByUserID(ctx context.Context, userID string) ([]Project, error)
	GetTeamByID(ctx context.Context, id string) (Team, error)
	GetTeamsByUserID(ctx context.Context, userID string) ([]Team, error)
	GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error)
	GetUserByEmailWithoutPassword(ctx context.Context, email string) (GetUserByEmailWithoutPasswordRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetViewByID(ctx context.Context, id string) (View, error)
	GetWorkspaceByID(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceByUserID(ctx context.Context, ownerID string) ([]Workspace, error)
	IsMemberInTeam(ctx context.Context, arg IsMemberInTeamParams) (int64, error)
	IsProjectExists(ctx context.Context, id string) (int64, error)
	IsTeamExists(ctx context.Context, id string) (int64, error)
	ListAssigneesByIssueID(ctx context.Context, issueID string) ([]User, error)
	ListGroupBysByViewID(ctx context.Context, viewID string) ([]string, error)
	ListIssuesByProjectID(ctx context.Context, projectID sql.NullString) ([]Issue, error)
	ListIssuesByTeamID(ctx context.Context, teamID string) ([]Issue, error)
	ListIssuesByUserID(ctx context.Context, userID string) ([]ListIssuesByUserIDRow, error)
	ListIssuesByViewID(ctx context.Context, viewID string) ([]Issue, error)
	ListProjectMembers(ctx context.Context, projectID string) ([]User, error)
	ListProjectsByWorkspace(ctx context.Context, workspaceID string) ([]ListProjectsByWorkspaceRow, error)
	ListTeamMembers(ctx context.Context, teamID string) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListViewsByUser(ctx context.Context, userID string) ([]View, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]User, error)
	ListWorkspacesWithMembersByUserID(ctx context.Context, arg ListWorkspacesWithMembersByUserIDParams) ([]ListWorkspacesWithMembersByUserIDRow, error)
	RemoveAssigneeFromIssue(ctx context.Context, arg RemoveAssigneeFromIssueParams) error
	RemoveGroupByFromView(ctx context.Context, arg RemoveGroupByFromViewParams) error
	RemoveIssueFromView(ctx context.Context, arg RemoveIssueFromViewParams) error
	RemoveMemberFromProject(ctx context.Context, arg RemoveMemberFromProjectParams) error
	RemoveMemberFromTeam(ctx context.Context, arg RemoveMemberFromTeamParams) error
	RemoveMemberFromWorkspace(ctx context.Context, arg RemoveMemberFromWorkspaceParams) error
	RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) error
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateRoles(ctx context.Context, arg UpdateRolesParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) error
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error
}

var _ Querier = (*Queries)(nil)
